version: '3.1'

volumes:
  doppio-db:
    external: true
  caddy_local:

services:

  mongo:
    image: doppio_mongo
    restart: always
    build:
        context: .
        dockerfile: ./compose/mongo/Dockerfile
    env_file:
      - ./.envs/.local/.mongo
    volumes:
      - doppio-db:/data/db

        #   mongoexpress:
        #     image: mongo-express
        #     restart: always
        #     ports:
        #       - "8081:8081"
        #     env_file:
        #       - ./.envs/.mongoexpress
        #     depends_on:
        #       - mongo

  eve:
    image: doppio_eve
    build:
        context: .
        dockerfile: ./compose/eve/Dockerfile
    env_file:
      - ./.envs/.local/.eve
    environment:
      EVE_DEBUG_MODE: "False"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mongo
    command: python run.py runserver 0.0.0.0:5000

  caddy:
    image: doppio_caddy
    build:
      context: .
      dockerfile: ./compose/caddy/local/Dockerfile
    depends_on:
      - eve
    volumes:
      - caddy_local:/root/.caddy
      - ./static:/srv/static
    env_file:
      - ./.envs/.local/.caddy
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
