version: '2'
services:
  db:
    #image: mongo
    build:
        context: .
        dockerfile: Dockerfile-mongo
    volumes:
      - playbill-db:/data/db
  web:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8080:5000"
    depends_on:
      - db
    command: python run.py runserver 0.0.0.0:5000
volumes:
  playbill-db:
    external: true
