version: '3'

volumes:
  playbill-db:
    external: true
  caddy_local:

services:

  mongo:
    image: pdb_mongo
    restart: always
    build:
        context: .
        dockerfile: Dockerfile-mongo
    env_file: 
      - ./.envs/.local/.mongo
    volumes:
      - playbill-db:/data/db

  # mongoexpress:
    #   image: mongo-express
    #   restart: always
    #   ports: 
    #     - "8081:8081"
    #   env_file:
    #     - ./.envs/.mongoexpress
    #   depends_on:
    #     - mongo

  eve:
    image: pdb_eve
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - ./.envs/.local/.eve
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mongo
    command: python run.py runserver 0.0.0.0:5000

  caddy:
    image: pdb_caddy_local
    build:
      context: .
      dockerfile: ./compose/caddy/local/Dockerfile
    depends_on:
      - eve
    volumes:
      - caddy_local:/root/.caddy
    env_file:
      - ./.envs/.local/.caddy
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
