version: '3'

volumes:
  doppio-db:
    external: true
  caddy_production:

services:

  mongo:
    image: doppio_mongo_production
    build:
      context: .
      dockerfile: ./compose/mongo/Dockerfile
    restart: always
    env_file: 
      - ./.envs/.production/.mongo
    volumes:
      - playbill-db:/data/db

  # mongoexpress:
    #   image: mongo-express
    #   restart: always
    #   ports: 
    #     - "8081:8081"
    #   env_file:
    #     - ./.envs/.mongoexpress
    #   depends_on:
    #     - mongo

  eve:
    image: doppio_eve_production
    build:
      context: .
      dockerfile: ./compose/eve/Dockerfile
    env_file:
      - ./.envs/.production/.eve
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mongo
    command: gunicorn --bind 0.0.0.0:5000 wsgi

  caddy:
    image: doppio_caddy_production
    build:
      context: .
      dockerfile: ./compose/caddy/production/Dockerfile
    depends_on:
      - eve
    volumes:
      - caddy_production:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
