main_schema = {  
    "medievalChronicles":{  
        "type":"dict",
        "schema":{  
            "chronicles":{  
                "order":1,
                "type":"dict",
                "schema":{  
                    "geography":{  
                        "order":1,
                        "type":"list",
                        "schema":{  
                            "type":"dict",
                            "schema":{  
                                "region":{  
                                    "order":1,
                                    "type":"string"
                                },
                                "city":{  
                                    "order":2,
                                    "type":"string"
                                },
                                "freeText":{  
                                    "order":3,
                                    "type":"string",
                                    "formType":"textarea"
                                }
                            }
                        }
                    },
                    "language":{  
                        "order":2,
                        "type":"dict",
                        "schema":{  
                            "learned":{  
                                "type":"string",
                                "formType":"select",
                                "allowed":[  
                                    "Latin",
                                    "Greek",
                                    "Church Slavonic",
                                    "Hebrew",
                                    "Arabic"
                                ]
                            },
                            "vernacular":{  
                                "type":"string",
                                "formType":"select",
                                "allowed":[  
                                    "English",
                                    "German",
                                    "Czech",
                                    "Polish",
                                    "Croatian",
                                    "Dutch",
                                    "Italian",
                                    "Spanish"
                                ]
                            }
                        }
                    },
                    "period":{  
                        "order":3,
                        "type":"dict",
                        "schema":{  
                            "period":{  
                                "type":"string",
                                "required":True,
                                "formType":"select",
                                "allowed":[  
                                    "pre-900",
                                    "900-950",
                                    "950-1000",
                                    "1000-1050",
                                    "1050-1100",
                                    "1100-1150",
                                    "1150-1200",
                                    "1200-1250",
                                    "1250-1300",
                                    "1300-1350",
                                    "1350-1400",
                                    "1400-1450",
                                    "1450-1500",
                                    "post-1500"
                                ]
                            }
                        }
                    },
                    "sourcesMentionedByAuthor":{  
                        "order":4,
                        "type":"dict",
                        "schema":{  
                            "worksOfClassicalAntiquity":{  
                                "type":"dict",
                                "order":1,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "previousChronicles":{  
                                "type":"dict",
                                "order":2,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "documentsAndCharters":{  
                                "type":"dict",
                                "order":3,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "witnesses":{  
                                "type":"dict",
                                "order":4,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "secondhandOralAccounts":{  
                                "type":"dict",
                                "order":5,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "content":{  
                "order":2,
                "type":"dict",
                "schema":{  
                    "theChronicleIncludesBiblicalHistory":{  
                        "order":1,
                        "type":"boolean",
                        "formType":"checkbox"
                    },
                    "theChronicleIncludesClassicalMyths":{  
                        "order":2,
                        "type":"boolean",
                        "formType":"checkbox"
                    },
                    "theChronicleIncludesLocalOralTraditionNarratives":{  
                        "order":3,
                        "type":"boolean",
                        "formType":"checkbox"
                    },
                    "theChronicleIncludesMythsOfOrigin":{  
                        "order":4,
                        "type":"boolean",
                        "formType":"checkbox"
                    },
                    "theChronicleIncludesEtymologies":{  
                        "order":5,
                        "type":"boolean",
                        "formType":"checkbox",
                        "documentation":"If the legendary section features origin stories, do the origin stories feature etymologies?"
                    },
                    "namesOfIndividuals":{  
                        "order":6,
                        "type":"list",
                        "schema":{  
                            "type":"dict",
                            "schema":{  
                                "name":{  
                                    "type":"string"
                                },
                                "source":{  
                                    "type":"string",
                                    "formType":"select",
                                    "allowed":[  
                                        "Biblical",
                                        "Classical",
                                        "Historically Known",
                                        "Local Folk",
                                        "Foreign Folk"
                                    ]
                                }
                            }
                        }
                    },
                    "namesOfGroups":{  
                        "order":7,
                        "type":"list",
                        "schema":{  
                            "type":"dict",
                            "schema":{  
                                "name":{  
                                    "type":"string"
                                },
                                "source":{  
                                    "type":"string",
                                    "formType":"select",
                                    "allowed":[  
                                        "Biblical",
                                        "Classical",
                                        "Historically Known",
                                        "Legendary"
                                    ]
                                }
                            }
                        }
                    },
                    "events":{  
                        "order":8,
                        "type":"dict",
                        "schema":{  
                            "flood":{  
                                "type":"dict",
                                "order":1,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "wandering":{  
                                "type":"dict",
                                "order":2,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "followingAnAnimal":{  
                                "type":"dict",
                                "order":3,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "escapingFromPreviousLocation":{  
                                "type":"dict",
                                "order":4,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "comingToDestinedLand":{  
                                "type":"dict",
                                "order":5,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "speechActOfNaming":{  
                                "type":"dict",
                                "order":6,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "other":{  
                                "type":"dict",
                                "order":7,
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            }
                        }
                    },
                    "places":{  
                        "order":9,
                        "type":"list",
                        "schema":{  
                            "type":"string",
                            "formType":"textarea"
                        }
                    },
                    "genealogies":{  
                        "order":10,
                        "type":"dict",
                        "schema":{  
                            "fromTheTowerOfBabel":{  
                                "order":1,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "genealogyFromNoah'sSons":{  
                                "order":2,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "genealogyFromAnotherBiblicalCharacter":{  
                                "order":3,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "fromTheTrojans":{  
                                "order":4,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "fromTheGreeks":{  
                                "order":5,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "fromTheRomans":{  
                                "order":6,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "fromOther":{  
                                "order":6,
                                "type":"dict",
                                "schema":{  
                                    "mentioned":{  
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            }
                        }
                    },
                    "attitudeOfAuthorTowardsOralTradition":{  
                        "order":11,
                        "type":"dict",
                        "schema":{  
                            "authorTalksAboutProblemOfMyths":{  
                                "order":1,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "documentation":"Does the author talk about the problem of including folk stories and myths?",
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "order":2,
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorJustifiesTheInclusionOfMyths":{  
                                "order":2,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "documentation":"Is the inclusion of folk stories justified by the author?",
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "order":2,
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorMentionsSources":{  
                                "order":3,
                                "type":"dict",
                                "schema":{  
                                    "fromTheStoriesOfElders":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "fromMinstrelsOrTroubadours":{  
                                        "order":2,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "fromOtherChronicles":{  
                                        "order":3,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "fromWrittenSources":{  
                                        "order":4,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "fromSpecificPeople":{  
                                        "order":5,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "fromOther":{  
                                        "order":6,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "notes":{  
                                        "order":7,
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "etymologies":{  
                "order":3,
                "type":"list",
                "schema":{  
                    "type":"dict",
                    "schema":{  
                        "etymologyText":{  
                            "order":1,
                            "type":"string",
                            "documentation":"Enter the etymology in the text box.",
                            "formType":"textarea"
                        },
                        "sectionOfTheChronicle":{  
                            "order":2,
                            "type":"string",
                            "documentation":"In what section does this etymology occur?",
                            "allowed":[  
                                "preface/dedication",
                                "biblical section",
                                "folk history section",
                                "distant documented past",
                                "recent documented past",
                                "very recent/present",
                                "other"
                            ],
                            "formType":"select"
                        },
                        "etymonType":{  
                            "order":3,
                            "type":"string",
                            "documentation":"What kind of etymology is it?",
                            "allowed":[  
                                "person name",
                                "ruler name",
                                "ethnonym",
                                "country name",
                                "city name",
                                "river name",
                                "place name (mountain, forest region, etc.)",
                                "quality or description (action verb, adjective)",
                                "social custom"
                            ],
                            "formType":"select"
                        },
                        "derivationAccordingToIsidore":{  
                            "order":4,
                            "type":"string",
                            "documentation":"Derivation according to Isidore",
                            "allowed":[  
                                "ex origo",
                                "ex causa",
                                "ex contrario"
                            ],
                            "formType":"select"
                        },
                        "etymologyIsNotOriginal":{  
                            "order":6,
                            "type":"dict",
                            "schema":{  
                                "etymologyIsTakenFromAnotherSource":{  
                                    "order":1,
                                    "documentation":"Is the etymology taken from another source?",
                                    "type":"boolean",
                                    "formType":"checkbox"
                                },
                                "description":{  
                                    "order":2,
                                    "documentation":"If the etymology is taken from another source, what is the source?",
                                    "type":"string",
                                    "formType":"textarea"
                                }
                            }
                        },
                        "narrativeEtymologies":{  
                            "order":7,
                            "type":"dict",
                            "schema":{  
                                "etymologyHasRelatedStory":{  
                                    "order":1,
                                    "documentation":"Does the etymology have a related story or narrative?",
                                    "type":"boolean",
                                    "formType":"checkbox"
                                },
                                "description":{  
                                    "order":2,
                                    "documentation":"If the etymology has a related story/narrative, summarize the plot.",
                                    "type":"string",
                                    "formType":"textarea"
                                }
                            }
                        },
                        "etymologyAndSpeechAct":{  
                            "order":8,
                            "type":"dict",
                            "schema":{  
                                "etymologyInvolvesSpeechAct":{  
                                    "order":1,
                                    "documentation":"Does the etymology involve a speech act.",
                                    "type":"boolean",
                                    "formType":"checkbox"
                                },
                                "description":{  
                                    "order":2,
                                    "documentation":"If the etymology involves a speech act, detail it.",
                                    "type":"string",
                                    "formType":"textarea"
                                }
                            }
                        },
                        "sourceLanguage":{  
                            "order":5,
                            "type":"list",
                            "schema":{  
                                "type":"dict",
                                "schema":{  
                                    "sourceLanguage":{  
                                        "type":"string",
                                        "documentation":"Etymology's source language",
                                        "allowed":[  
                                            "Latin",
                                            "Greek",
                                            "Hebrew",
                                            "Vernacular"
                                        ],
                                        "formType":"select",
                                        "order":1
                                    },
                                    "vernacularLanguage":{  
                                        "type":"string",
                                        "documentation":"If the source language is vernacular, which type is it?",
                                        "order":2
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "authorsAndGoals":{  
                "order":4,
                "type":"dict",
                "schema":{  
                    "personalInfoAboutAuthor":{  
                        "order":1,
                        "type":"dict",
                        "schema":{  
                            "authorIsAnonymous":{  
                                "order":0,
                                "type":"boolean",
                                "formType":"checkbox"
                            },
                            "authorName":{  
                                "type":"string",
                                "documentation":"If the author's name is known, what is it?",
                                "order":1
                            },
                            "authorNickname":{  
                                "type":"string",
                                "documentation":"If the author's name is not known, what is their nickname (if they have one)?",
                                "order":2
                            },
                            "authorOccupation":{  
                                "type":"string",
                                "documentation":"If the author's occupation is known, what is it?",
                                "order":3
                            },
                            "authorEducation":{  
                                "type":"string",
                                "documentation":"If the author's education is known, select one:",
                                "allowed":[  
                                    "Church/chapter school",
                                    "Monestary",
                                    "University",
                                    "Private",
                                    "Other"
                                ],
                                "formType":"select",
                                "order":4
                            },
                            "authorComposedOtherWorks":{  
                                "type":"string",
                                "documentation":"Has the author composed other works?",
                                "allowed":[  
                                    "yes",
                                    "no",
                                    "unknown"
                                ],
                                "formType":"select",
                                "order":5
                            },
                            "otherWorks":{  
                                "type":"string",
                                "documentation":"If the author has composed other works, what are they?",
                                "formType":"textarea",
                                "order":6
                            },
                            "additionalNotes":{  
                                "type":"string",
                                "documentation":"If the author says anything else about his biography, what is it?",
                                "formType":"textarea",
                                "order":7
                            }
                        }
                    },
                    "causaAndModusScribendi":{  
                        "order":2,
                        "type":"dict",
                        "schema":{  
                            "authorTalksAboutTaskOfHistorian":{  
                                "order":1,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author says anything about his understanding of a historian's task, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutTruth":{  
                                "order":2,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author talks about truth being important for a historian, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutReasonForWriting":{  
                                "order":3,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "documentation":"If the author gives a reason for writing his work, what does he say?",
                                        "order":2,
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutIntendedAudience":{  
                                "order":4,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author mentions the intended audience, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutReliabilityOfSources":{  
                                "order":5,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author shows awareness of the reliability of sources, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutImportanceOfLanguage":{  
                                "order":6,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "documentation":"Is the inclusion of folk stories justified by the author?",
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author acknowledges the importance of language and/or grammar, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutGrammarians":{  
                                "order":7,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author refers to grammarians or other scholars, who does he refer to?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutHisOwnWriting":{  
                                "order":8,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author comments about his own language, style, or research skills, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorUsesVerbsThatSignifyResearch":{  
                                "order":9,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author uses any 'intellectual verbs' that signify research ('learn, study'), what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutSimplicityAsPositive":{  
                                "order":10,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author mentions simplicity of style as a positive feature, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutClarityAsPositive":{  
                                "order":11,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author mentions clarity of style as a positive feature, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutBrevityAsPositive":{  
                                "order":12,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author mentions brevity as a positive feature, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorComparesHisWorkToOthers":{  
                                "order":13,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author compares his work/style to others, who?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutCriticismFromOthers":{  
                                "order":14,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author says anything about other historians or those who might judge him, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorTalksAboutBeingRidiculed":{  
                                "order":15,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author mentions a possibility of being ridiculed or laughed at, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "authorAppealsToAddresseeToAcceptHisWork":{  
                                "order":16,
                                "type":"dict",
                                "schema":{  
                                    "yes":{  
                                        "order":1,
                                        "type":"boolean",
                                        "formType":"checkbox"
                                    },
                                    "description":{  
                                        "order":2,
                                        "documentation":"If the author appeals to his addressee or reader to accept his work, what does he say?",
                                        "type":"string",
                                        "formType":"textarea"
                                    }
                                }
                            },
                            "additionalCommentsAboutCausaAndModusScribendi":{  
                                "order":16,
                                "type":"string",
                                "formType":"textarea"
                            }
                        }
                    }
                }
            }
        }
    }
}